// Auto-generated. Do not edit!

// (in-package cob_people_detection.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class addDataFeedback {
  constructor() {
    this.images_captured = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type addDataFeedback
    // Serialize message field [images_captured]
    bufferInfo = _serializer.int32(obj.images_captured, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type addDataFeedback
    let tmp;
    let len;
    let data = new addDataFeedback();
    // Deserialize message field [images_captured]
    tmp = _deserializer.int32(buffer);
    data.images_captured = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'cob_people_detection/addDataFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0bd9d2345b5b8d85a254a7569f431459';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback message
    int32 images_captured			# the number of images already captured
    
    
    `;
  }

};

module.exports = addDataFeedback;
