// Auto-generated. Do not edit!

// (in-package cob_people_detection.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class loadModelGoal {
  constructor() {
    this.labels = [];
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type loadModelGoal
    // Serialize the length for message field [labels]
    bufferInfo = _serializer.uint32(obj.labels.length, bufferInfo);
    // Serialize message field [labels]
    obj.labels.forEach((val) => {
      bufferInfo = _serializer.string(val, bufferInfo);
    });
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type loadModelGoal
    let tmp;
    let len;
    let data = new loadModelGoal();
    // Deserialize array length for message field [labels]
    tmp = _deserializer.uint32(buffer);
    len = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [labels]
    data.labels = new Array(len);
    for (let i = 0; i < len; ++i) {
      tmp = _deserializer.string(buffer);
      data.labels[i] = tmp.data;
      buffer = tmp.buffer;
    }
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'cob_people_detection/loadModelGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '17b562487ca772bdfa2c078ef00d870f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Loads a recognition model for the face recognizer from disc or database
    #
    # goal message
    string[] labels		# a list of labels of persons that shall be recognized
    
    `;
  }

};

module.exports = loadModelGoal;
