// Auto-generated. Do not edit!

// (in-package face_detector.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let people_msgs = _finder('people_msgs');

//-----------------------------------------------------------

class FaceDetectorResult {
  constructor() {
    this.face_positions = [];
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type FaceDetectorResult
    // Serialize the length for message field [face_positions]
    bufferInfo = _serializer.uint32(obj.face_positions.length, bufferInfo);
    // Serialize message field [face_positions]
    obj.face_positions.forEach((val) => {
      bufferInfo = people_msgs.msg.PositionMeasurement.serialize(val, bufferInfo);
    });
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type FaceDetectorResult
    let tmp;
    let len;
    let data = new FaceDetectorResult();
    // Deserialize array length for message field [face_positions]
    tmp = _deserializer.uint32(buffer);
    len = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [face_positions]
    data.face_positions = new Array(len);
    for (let i = 0; i < len; ++i) {
      tmp = people_msgs.msg.PositionMeasurement.deserialize(buffer);
      data.face_positions[i] = tmp.data;
      buffer = tmp.buffer;
    }
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'face_detector/FaceDetectorResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b5dc843df183dbab7f0ab2f5ef5b6f9d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    people_msgs/PositionMeasurement[] face_positions
    
    ================================================================================
    MSG: people_msgs/PositionMeasurement
    Header          header
    string          name
    string          object_id
    geometry_msgs/Point pos
    float64         reliability
    float64[9] 	covariance
    byte            initialization
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

};

module.exports = FaceDetectorResult;
