// Generated by gencpp from file kinects_human_tracking/GetBackground.msg
// DO NOT EDIT!


#ifndef KINECTS_HUMAN_TRACKING_MESSAGE_GETBACKGROUND_H
#define KINECTS_HUMAN_TRACKING_MESSAGE_GETBACKGROUND_H

#include <ros/service_traits.h>


#include <kinects_human_tracking/GetBackgroundRequest.h>
#include <kinects_human_tracking/GetBackgroundResponse.h>


namespace kinects_human_tracking
{

struct GetBackground
{

typedef GetBackgroundRequest Request;
typedef GetBackgroundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBackground
} // namespace kinects_human_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinects_human_tracking::GetBackground > {
  static const char* value()
  {
    return "81e2a8170330fb0b513ae368769739c5";
  }

  static const char* value(const ::kinects_human_tracking::GetBackground&) { return value(); }
};

template<>
struct DataType< ::kinects_human_tracking::GetBackground > {
  static const char* value()
  {
    return "kinects_human_tracking/GetBackground";
  }

  static const char* value(const ::kinects_human_tracking::GetBackground&) { return value(); }
};


// service_traits::MD5Sum< ::kinects_human_tracking::GetBackgroundRequest> should match 
// service_traits::MD5Sum< ::kinects_human_tracking::GetBackground > 
template<>
struct MD5Sum< ::kinects_human_tracking::GetBackgroundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinects_human_tracking::GetBackground >::value();
  }
  static const char* value(const ::kinects_human_tracking::GetBackgroundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinects_human_tracking::GetBackgroundRequest> should match 
// service_traits::DataType< ::kinects_human_tracking::GetBackground > 
template<>
struct DataType< ::kinects_human_tracking::GetBackgroundRequest>
{
  static const char* value()
  {
    return DataType< ::kinects_human_tracking::GetBackground >::value();
  }
  static const char* value(const ::kinects_human_tracking::GetBackgroundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinects_human_tracking::GetBackgroundResponse> should match 
// service_traits::MD5Sum< ::kinects_human_tracking::GetBackground > 
template<>
struct MD5Sum< ::kinects_human_tracking::GetBackgroundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinects_human_tracking::GetBackground >::value();
  }
  static const char* value(const ::kinects_human_tracking::GetBackgroundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinects_human_tracking::GetBackgroundResponse> should match 
// service_traits::DataType< ::kinects_human_tracking::GetBackground > 
template<>
struct DataType< ::kinects_human_tracking::GetBackgroundResponse>
{
  static const char* value()
  {
    return DataType< ::kinects_human_tracking::GetBackground >::value();
  }
  static const char* value(const ::kinects_human_tracking::GetBackgroundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINECTS_HUMAN_TRACKING_MESSAGE_GETBACKGROUND_H
