// Auto-generated. Do not edit!

// (in-package cob_object_detection_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class DetectObjectsFeedback {
  constructor() {
    this.percent_complete = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type DetectObjectsFeedback
    // Serialize message field [percent_complete]
    bufferInfo = _serializer.float32(obj.percent_complete, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type DetectObjectsFeedback
    let tmp;
    let len;
    let data = new DetectObjectsFeedback();
    // Deserialize message field [percent_complete]
    tmp = _deserializer.float32(buffer);
    data.percent_complete = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'cob_object_detection_msgs/DetectObjectsFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd342375c60a5a58d3bc32664070a1368';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # The feedback
    float32 percent_complete
    
    
    `;
  }

};

module.exports = DetectObjectsFeedback;
