// Auto-generated. Do not edit!

// (in-package cob_object_detection_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class DetectObjectsGoal {
  constructor() {
    this.object_name = new std_msgs.msg.String();
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type DetectObjectsGoal
    // Serialize message field [object_name]
    bufferInfo = std_msgs.msg.String.serialize(obj.object_name, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type DetectObjectsGoal
    let tmp;
    let len;
    let data = new DetectObjectsGoal();
    // Deserialize message field [object_name]
    tmp = std_msgs.msg.String.deserialize(buffer);
    data.object_name = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'cob_object_detection_msgs/DetectObjectsGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'adb33ef101026c3e15d799e3decf403f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # The goal
    std_msgs/String object_name
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

};

module.exports = DetectObjectsGoal;
