// Auto-generated. Do not edit!

// (in-package cob_object_detection_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class TrainObjectGoal {
  constructor() {
    this.object_name = '';
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type TrainObjectGoal
    // Serialize message field [object_name]
    bufferInfo = _serializer.string(obj.object_name, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type TrainObjectGoal
    let tmp;
    let len;
    let data = new TrainObjectGoal();
    // Deserialize message field [object_name]
    tmp = _deserializer.string(buffer);
    data.object_name = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'cob_object_detection_msgs/TrainObjectGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2f12226348d323c2e5b2031b3da53f1b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # The goal
    string object_name
    
    `;
  }

};

module.exports = TrainObjectGoal;
