// Auto-generated. Do not edit!

// (in-package cob_3d_mapping_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class TriggerGoal {
  constructor() {
    this.start = false;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type TriggerGoal
    // Serialize message field [start]
    bufferInfo = _serializer.bool(obj.start, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type TriggerGoal
    let tmp;
    let len;
    let data = new TriggerGoal();
    // Deserialize message field [start]
    tmp = _deserializer.bool(buffer);
    data.start = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'cob_3d_mapping_msgs/TriggerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '676aa7bfb3ec2071e814f2368dfd5fb5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Trigger
    #goal definition
    bool start
    
    `;
  }

};

module.exports = TriggerGoal;
